let userscore=0;
let comscore=0;
let choices=document.querySelectorAll(".choice");
const msg=document.querySelector(".m");
let you_score=document.querySelector(".you_score");
let com_score=document.querySelector(".Com_score");
const genComp=()=>//generated by computer
{
    let options=["rock","paper","scissor"];
    let idx= Math.floor(Math.random()*3);
    return options[idx];

}
const drawGame=()=>
{
    console.log("Game is draw");
    msg.innerText="Game was draw.Play again";
    msg.style.backgroundColor="rgb(18, 18, 96)";
}
const gameWinner=(userWin,userChoice,comChoice)=>
{
    if(userWin)
    {
        console.log("You won");
        userscore++;
        you_score.innerText=`${userscore}`;
        msg.innerText=`You won!.Your ${userChoice} beats ${comChoice}`;
        msg.style.backgroundColor="green";
    }
    else
    {
        console.log("You lost");
        comscore++;
        com_score.innerText=`${comscore}`;
        console.log("Computer Score: ",comscore);
        msg.innerText=`You lost.${comChoice} beats your ${userChoice}`;
        msg.style.backgroundColor="red";
    }
}
const playGame=(userChoice)=>
{
    console.log("user choice= ",userChoice);
    comChoice=genComp();
    console.log("computer Choice= ",comChoice);
    if(userChoice===comChoice)
    {
        //game is draw
        drawGame();
    }
    else
    {
        let userWin=true;
        if(userChoice==="paper")
        {
            //comp can have rock or scissor
            userWin=comChoice==="rock"?true:false;
        }
        else if(userChoice==="rock")
        {
            //comp can have paper or scissor
            userWin=comChoice==="scissor"?true:false;
        }
        else
        {
            //comp can have paper or rock
            userWin=comChoice==="paper"?true:false;
        }
        gameWinner(userWin,userChoice,comChoice);
    }
    
}
choices.forEach((choice)=>{
    choice.addEventListener("click",()=>
    {
       let userChoice=choice.getAttribute("id");
        
        playGame(userChoice);
    });
});
//Math.random():generates random number from 0-1 we can make them from 0-2 by multiply with 3
//Math.floor():gives integer value near to it